// sentences.js - Full pack (N5 -> N3) ~330 items
const LEX = {
  nouns: [
    {en:"school", ja:"がっこう", display:"学校"},
    {en:"station", ja:"えき", display:"駅"},
    {en:"store", ja:"みせ", display:"店"},
    {en:"library", ja:"としょかん", display:"図書館"},
    {en:"house", ja:"いえ", display:"家"},
    {en:"room", ja:"へや", display:"部屋"},
    {en:"book", ja:"ほん", display:"本"},
    {en:"water", ja:"みず", display:"水"},
    {en:"rice", ja:"ごはん", display:"ご飯"},
    {en:"bread", ja:"パン", display:"パン"},
    {en:"coffee", ja:"コーヒー", display:"コーヒー"},
    {en:"tea", ja:"おちゃ", display:"お茶"},
    {en:"apple", ja:"りんご", display:"りんご"},
    {en:"banana", ja:"バナナ", display:"バナナ"},
    {en:"orange", ja:"オレンジ", display:"オレンジ"},
    {en:"fish", ja:"さかな", display:"魚"},
    {en:"meat", ja:"にく", display:"肉"},
    {en:"vegetable", ja:"やさい", display:"野菜"},
    {en:"salad", ja:"サラダ", display:"サラダ"},
    {en:"soup", ja:"スープ", display:"スープ"},
    {en:"movie", ja:"えいが", display:"映画"},
    {en:"song", ja:"うた", display:"歌"},
    {en:"game", ja:"ゲーム", display:"ゲーム"},
    {en:"car", ja:"くるま", display:"車"},
    {en:"bicycle", ja:"じてんしゃ", display:"自転車"},
    {en:"motorbike", ja:"バイク", display:"バイク"},
    {en:"computer", ja:"コンピューター", display:"コンピューター"},
    {en:"phone", ja:"けいたい", display:"携帯"},
    {en:"telephone", ja:"でんわ", display:"電話"},
    {en:"letter", ja:"てがみ", display:"手紙"},
    {en:"email", ja:"メール", display:"メール"},
    {en:"gift", ja:"プレゼント", display:"プレゼント"},
    {en:"money", ja:"おかね", display:"お金"},
    {en:"wallet", ja:"さいふ", display:"財布"},
    {en:"time", ja:"じかん", display:"時間"},
    {en:"hour", ja:"じかん", display:"時間"},
    {en:"minute", ja:"ふん", display:"分"},
    {en:"friend", ja:"ともだち", display:"友達"},
    {en:"boyfriend", ja:"かれし", display:"彼氏"},
    {en:"girlfriend", ja:"かのじょ", display:"彼女"},
    {en:"teacher", ja:"せんせい", display:"先生"},
    {en:"student", ja:"がくせい", display:"学生"},
    {en:"classroom", ja:"きょうしつ", display:"教室"},
    {en:"family", ja:"かぞく", display:"家族"},
    {en:"mother", ja:"おかあさん", display:"お母さん"},
    {en:"father", ja:"おとうさん", display:"お父さん"},
    {en:"sister", ja:"いもうと", display:"妹"},
    {en:"brother", ja:"おにいさん", display:"お兄さん"},
    {en:"child", ja:"こども", display:"子ども"},
    {en:"baby", ja:"あかちゃん", display:"赤ちゃん"},
    {en:"man", ja:"おとこ", display:"男"},
    {en:"woman", ja:"おんな", display:"女"},
    {en:"cat", ja:"ねこ", display:"猫"},
    {en:"dog", ja:"いぬ", display:"犬"},
    {en:"bird", ja:"とり", display:"鳥"},
    {en:"horse", ja:"うま", display:"馬"},
    {en:"cow", ja:"うし", display:"牛"},
    {en:"mountain", ja:"やま", display:"山"},
    {en:"river", ja:"かわ", display:"川"},
    {en:"sea", ja:"うみ", display:"海"},
    {en:"lake", ja:"みずうみ", display:"湖"},
    {en:"island", ja:"しま", display:"島"},
    {en:"bridge", ja:"はし", display:"橋"},
    {en:"park", ja:"こうえん", display:"公園"},
    {en:"garden", ja:"にわ", display:"庭"},
    {en:"street", ja:"みち", display:"道"},
    {en:"road", ja:"どうろ", display:"道路"},
    {en:"city", ja:"まち", display:"町"},
    {en:"village", ja:"むら", display:"村"},
    {en:"country", ja:"くに", display:"国"},
    {en:"capital", ja:"しゅと", display:"首都"},
    {en:"weather", ja:"てんき", display:"天気"},
    {en:"sun", ja:"たいよう", display:"太陽"},
    {en:"moon", ja:"つき", display:"月"},
    {en:"star", ja:"ほし", display:"星"},
    {en:"rain", ja:"あめ", display:"雨"},
    {en:"snow", ja:"ゆき", display:"雪"},
    {en:"wind", ja:"かぜ", display:"風"},
    {en:"cloud", ja:"くも", display:"雲"},
    {en:"temperature", ja:"きおん", display:"気温"},
    {en:"season", ja:"きせつ", display:"季節"},
    {en:"spring", ja:"はる", display:"春"},
    {en:"summer", ja:"なつ", display:"夏"},
    {en:"autumn", ja:"あき", display:"秋"},
    {en:"winter", ja:"ふゆ", display:"冬"},
    {en:"breakfast", ja:"あさごはん", display:"朝ご飯"},
    {en:"lunch", ja:"ひるごはん", display:"昼ご飯"},
    {en:"dinner", ja:"ばんごはん", display:"晩ご飯"},
    {en:"snack", ja:"おやつ", display:"おやつ"},
    {en:"restaurant", ja:"レストラン", display:"レストラン"},
    {en:"cafe", ja:"カフェ", display:"カフェ"},
    {en:"shop", ja:"みせ", display:"店"},
    {en:"supermarket", ja:"スーパー", display:"スーパー"},
    {en:"market", ja:"いちば", display:"市場"},
    {en:"hospital", ja:"びょういん", display:"病院"},
    {en:"clinic", ja:"しんさつ", display:"診察"},
    {en:"bank", ja:"ぎんこう", display:"銀行"},
    {en:"post office", ja:"ゆうびんきょく", display:"郵便局"},
    {en:"police station", ja:"こうばん", display:"交番"},
    {en:"fire station", ja:"しょうぼうしょ", display:"消防署"},
    {en:"hotel", ja:"ホテル", display:"ホテル"},
    {en:"station building", ja:"えきびる", display:"駅ビル"},
    {en:"airport", ja:"くうこう", display:"空港"},
    {en:"ticket", ja:"きっぷ", display:"切符"},
    {en:"map", ja:"ちず", display:"地図"},
    {en:"museum", ja:"はくぶつかん", display:"博物館"},
    {en:"movie theater", ja:"えいがかん", display:"映画館"},
    {en:"theater", ja:"げきじょう", display:"劇場"},
    {en:"concert", ja:"コンサート", display:"コンサート"},
    {en:"music", ja:"おんがく", display:"音楽"},
    {en:"art", ja:"びじゅつ", display:"美術"},
    {en:"bookstore", ja:"ほんや", display:"本屋"},
    {en:"station platform", ja:"ホーム", display:"ホーム"},
    {en:"ticket counter", ja:"うりば", display:"売り場"},
    {en:"queue", ja:"ならび", display:"並び"},
    {en:"line", ja:"せん", display:"線"},
    {en:"bus", ja:"バス", display:"バス"},
    {en:"train", ja:"でんしゃ", display:"電車"},
    {en:"subway", ja:"ちかてつ", display:"地下鉄"},
    {en:"taxi", ja:"タクシー", display:"タクシー"},
    {en:"shop clerk", ja:"てんいん", display:"店員"},
    {en:"customer", ja:"きゃく", display:"客"},
    {en:"teacher (male)", ja:"きょうし", display:"教師"},
    {en:"employee", ja:"しゃいん", display:"社員"},
    {en:"manager", ja:"かちょう", display:"課長"},
    {en:"company", ja:"かいしゃ", display:"会社"}
  ],

  verbs: [
    {en:"to eat", ja:"たべる", display:"食べる"},
    {en:"to drink", ja:"のむ", display:"飲む"},
    {en:"to go", ja:"いく", display:"行く"},
    {en:"to come", ja:"くる", display:"来る"},
    {en:"to see/watch", ja:"みる", display:"見る"},
    {en:"to watch (TV)", ja:"テレビをみる", display:"テレビを見る"},
    {en:"to read", ja:"よむ", display:"読む"},
    {en:"to write", ja:"かく", display:"書く"},
    {en:"to buy", ja:"かう", display:"買う"},
    {en:"to sell", ja:"うる", display:"売る"},
    {en:"to sleep", ja:"ねる", display:"寝る"},
    {en:"to wake up", ja:"おきる", display:"起きる"},
    {en:"to run", ja:"はしる", display:"走る"},
    {en:"to walk", ja:"あるく", display:"歩く"},
    {en:"to wait", ja:"まつ", display:"待つ"},
    {en:"to speak", ja:"はなす", display:"話す"},
    {en:"to listen", ja:"きく", display:"聞く"},
    {en:"to study", ja:"べんきょうする", display:"勉強する"},
    {en:"to work", ja:"はたらく", display:"働く"},
    {en:"to play", ja:"あそぶ", display:"遊ぶ"},
    {en:"to open", ja:"あける", display:"開ける"},
    {en:"to close", ja:"しめる", display:"閉める"},
    {en:"to use", ja:"つかう", display:"使う"},
    {en:"to find", ja:"みつける", display:"見つける"},
    {en:"to lose", ja:"なくす", display:"無くす"},
    {en:"to think", ja:"おもう", display:"思う"},
    {en:"to know", ja:"しる", display:"知る"},
    {en:"to teach", ja:"おしえる", display:"教える"},
    {en:"to learn", ja:"まなぶ", display:"学ぶ"},
    {en:"to swim", ja:"およぐ", display:"泳ぐ"},
    {en:"to sing", ja:"うたう", display:"歌う"},
    {en:"to dance", ja:"おどる", display:"踊る"},
    {en:"to cook", ja:"つくる", display:"作る"},
    {en:"to clean", ja:"そうじする", display:"掃除する"},
    {en:"to drive", ja:"うんてんする", display:"運転する"},
    {en:"to help", ja:"てつだう", display:"手伝う"},
    {en:"to call", ja:"でんわする", display:"電話する"},
    {en:"to send", ja:"おくる", display:"送る"},
    {en:"to receive", ja:"うけとる", display:"受け取る"},
    {en:"to start", ja:"はじめる", display:"始める"},
    {en:"to finish", ja:"おわる", display:"終わる"},
    {en:"to change", ja:"かえる", display:"変える"},
    {en:"to remember", ja:"おぼえる", display:"覚える"},
    {en:"to forget", ja:"わすれる", display:"忘れる"},
    {en:"to prepare", ja:"じゅんびする", display:"準備する"},
    {en:"to decide", ja:"きめる", display:"決める"},
    {en:"to try", ja:"ためす", display:"試す"},
    {en:"to feel", ja:"かんじる", display:"感じる"},
    {en:"to smile", ja:"わらう", display:"笑う"},
    {en:"to cry", ja:"なく", display:"泣く"},
    {en:"to exist (inanimate)", ja:"ある", display:"ある"},
    {en:"to exist (animate)", ja:"いる", display:"いる"},
    {en:"to meet", ja:"あう", display:"会う"},
    {en:"to return", ja:"かえる", display:"帰る"},
    {en:"to visit", ja:"たずねる", display:"訪ねる"},
    {en:"to search", ja:"さがす", display:"探す"},
    {en:"to select", ja:"えらぶ", display:"選ぶ"},
    {en:"to accept", ja:"うけいれる", display:"受け入れる"},
    {en:"to reject", ja:"ことわる", display:"断る"},
    {en:"to notice", ja:"きづく", display:"気づく"},
    {en:"to imagine", ja:"そうぞうする", display:"想像する"},
    {en:"to spend (time)", ja:"すごす", display:"過ごす"},
    {en:"to spend (money)", ja:"つかう", display:"使う"},
    {en:"to improve", ja:"よくなる", display:"良くなる"},
    {en:"to collect", ja:"あつめる", display:"集める"},
    {en:"to plan", ja:"けいかくする", display:"計画する"},
    {en:"to recommend", ja:"すすめる", display:"勧める"},
    {en:"to cancel", ja:"キャンセルする", display:"キャンセルする"},
    {en:"to book", ja:"よやくする", display:"予約する"},
    {en:"to order", ja:"ちゅうもんする", display:"注文する"},
    {en:"to taste", ja:"あじわう", display:"味わう"},
    {en:"to borrow", ja:"かりる", display:"借りる"},
    {en:"to lend", ja:"かす", display:"貸す"},
    {en:"to teach (polite)", ja:"おしえます", display:"教えます"},
    {en:"to worry", ja:"しんぱいする", display:"心配する"}
  ],

  adjectives: [
    {en:"delicious", ja:"おいしい", display:"美味しい"},
    {en:"tasty", ja:"おいしい", display:"美味しい"},
    {en:"beautiful", ja:"きれい", display:"綺麗"},
    {en:"clean", ja:"きれいな", display:"綺麗な"},
    {en:"small", ja:"ちいさい", display:"小さい"},
    {en:"big", ja:"おおきい", display:"大きい"},
    {en:"easy", ja:"かんたん", display:"簡単"},
    {en:"difficult", ja:"むずかしい", display:"難しい"},
    {en:"fun", ja:"たのしい", display:"楽しい"},
    {en:"interesting", ja:"おもしろい", display:"面白い"},
    {en:"boring", ja:"つまらない", display:"詰まらない"},
    {en:"hot (weather)", ja:"あつい", display:"暑い"},
    {en:"cold (weather)", ja:"さむい", display:"寒い"},
    {en:"hot (object)", ja:"あつい", display:"熱い"},
    {en:"cold (object)", ja:"つめたい", display:"冷たい"},
    {en:"fast", ja:"はやい", display:"速い"},
    {en:"slow", ja:"おそい", display:"遅い"},
    {en:"young", ja:"わかい", display:"若い"},
    {en:"old (person)", ja:"としをとった", display:"年を取った"},
    {en:"new", ja:"あたらしい", display:"新しい"},
    {en:"old (thing)", ja:"ふるい", display:"古い"},
    {en:"strong", ja:"つよい", display:"強い"},
    {en:"weak", ja:"よわい", display:"弱い"},
    {en:"cheap", ja:"やすい", display:"安い"},
    {en:"expensive", ja:"たかい", display:"高い"},
    {en:"quiet", ja:"しずかな", display:"静かな"},
    {en:"noisy", ja:"うるさい", display:"煩い"},
    {en:"healthy", ja:"げんきな", display:"元気な"},
    {en:"tired", ja:"つかれた", display:"疲れた"},
    {en:"busy", ja:"いそがしい", display:"忙しい"},
    {en:"free (time)", ja:"ひま", display:"暇"},
    {en:"important", ja:"たいせつ", display:"大切"},
    {en:"useful", ja:"やくだつ", display:"役立つ"},
    {en:"dangerous", ja:"あぶない", display:"危ない"},
    {en:"safe", ja:"あんぜん", display:"安全"},
    {en:"comfortable", ja:"らく", display:"楽"},
    {en:"annoying", ja:"めんどう", display:"面倒"},
    {en:"famous", ja:"ゆうめい", display:"有名"},
    {en:"modern", ja:"げんだいてき", display:"現代的"},
    {en:"ancient", ja:"こだい", display:"古代"},
    {en:"happy", ja:"うれしい", display:"嬉しい"},
    {en:"sad", ja:"かなしい", display:"悲しい"},
    {en:"angry", ja:"おこった", display:"怒った"},
    {en:"calm", ja:"おだやか", display:"穏やか"},
    {en:"polite", ja:"ていねい", display:"丁寧"},
    {en:"rude", ja:"しつれい", display:"失礼"},
    {en:"rich", ja:"おかねもち", display:"お金持ち"},
    {en:"poor", ja:"まずしい", display:"貧しい"},
    {en:"sweet", ja:"あまい", display:"甘い"},
    {en:"sour", ja:"すっぱい", display:"酸っぱい"},
    {en:"bitter", ja:"にがい", display:"苦い"},
    {en:"spicy", ja:"からい", display:"辛い"},
    {en:"soft", ja:"やわらかい", display:"柔らかい"},
    {en:"hard", ja:"かたい", display:"硬い"},
    {en:"wide", ja:"ひろい", display:"広い"},
    {en:"narrow", ja:"せまい", display:"狭い"},
    {en:"bright", ja:"あかるい", display:"明るい"},
    {en:"dark", ja:"くらい", display:"暗い"},
    {en:"delicate", ja:"こまかい", display:"細かい"},
    {en:"useful (again)", ja:"やくだつ", display:"役立つ"}
  ],

  templates: {
    N5: [
      {en:"{S} will {V} the {O}.", ja:"{S}{O}を{V}", hint:"basic SOV"},
      {en:"{S} likes the {O}.", ja:"{S}{O}がすきです", hint:"like noun"},
      {en:"{S} will go to the {P}.", ja:"{S}{P}にいきます", hint:"go place"},
      {en:"{S} did {V} the {O}.", ja:"{S}{O}を{V}ました", hint:"past tense"},
      {en:"Is {S} {V}ing the {O}?", ja:"{S}{O}を{V}ていますか", hint:"progressive"},
      {en:"{S} has the {O}.", ja:"{S}{O}をもっています", hint:"possession (polite)"},
      {en:"Where is the {O}?", ja:"{O}はどこですか", hint:"where question"},
      {en:"How many {O} are there?", ja:"{O}はいくつですか", hint:"count question"},
      {en:"{S} opens the {O}.", ja:"{S}{O}をあけます", hint:"open"},
      {en:"{S} closes the {O}.", ja:"{S}{O}をしめます", hint:"close"}
    ],
    N4: [
      {en:"{S} wants to {V} the {O}.", ja:"{S}{O}を{V}たいです", hint:"want to"},
      {en:"{S} can {V} the {O}.", ja:"{S}{O}を{V}ことができます", hint:"ability"},
      {en:"{S} {T} {V} the {O}.", ja:"{S}{T}{O}を{V}", hint:"time + action"},
      {en:"{S} bought the {O} at the {P}.", ja:"{S}{P}で{O}をかいました", hint:"buy at place"},
      {en:"{S} went to the {P} and {V}.", ja:"{S}{P}へいって{V}", hint:"go and verb"},
      {en:"I think {S} {V} the {O}.", ja:"{S}{O}を{V}とおもいます", hint:"opinion"},
      {en:"{S} will {V} after {T}.", ja:"{S}{T}のあとで{V}", hint:"after time"},
      {en:"{S} has {O} already.", ja:"{S}はもう{O}をもっています", hint:"already"},
      {en:"Please {V} the {O}.", ja:"{O}を{V}てください", hint:"request"},
      {en:"{S} often {V} the {O}.", ja:"{S}はよく{O}を{V}", hint:"frequency"}
    ],
    N3: [
      {en:"{S} started to {V} the {O}.", ja:"{S}{O}を{V}はじめました", hint:"start doing"},
      {en:"{S} seems to {V} the {O}.", ja:"{S}{O}を{V}ようです", hint:"seems like"},
      {en:"While {S} {V}, {S} {V}.", ja:"{S}{O}を{V}ながら{V}", hint:"while doing"},
      {en:"{S} has never been to the {P}.", ja:"{S}{P}へいったことがありません", hint:"experience never"},
      {en:"It is said that {S} {V} the {O}.", ja:"{S}{O}を{V}そうです", hint:"hearsay"},
      {en:"If {S} {V}, {S} will {V}.", ja:"もし{S}{O}を{V}なら、{S}{O}を{V}", hint:"conditional"},
      {en:"Because {S} {V}, {S} {V}.", ja:"{S}{O}を{V}から、{S}{O}を{V}", hint:"reason"},
      {en:"Although {S} {V}, {S} {V}.", ja:"{S}{O}を{V}のに、{S}{O}を{V}", hint:"contrast"},
      {en:"{S} intends to {V} the {O}.", ja:"{S}{O}を{V}つもりです", hint:"intent"},
      {en:"{S} had been {V}ing the {O}.", ja:"{S}{O}を{V}ていました", hint:"past progressive"}
    ]
  }
};

if(typeof window !== "undefined") window.LEX = LEX;